# Site settings
title: Livret d'accueil
email: contact@airbnb.com
description: Livret d'accueil numérique pour voyageurs
baseurl: ""
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

