# Site settings
title: Livret d'accueil
email: contact@airbnb.com
description: Livret d'accueil numérique pour voyageurs
baseurl: ""
url: ""

# Multilingual settings
languages: ["fr", "en", "de", "es"]
default_lang: "fr"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
